services:
  app:
    build:
      context: .
    ports:
      - 8000:8000      # match the port Railway uses
    env_file:
      - .env           # load your local .env
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - 3306:3306