version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: resume_bot
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"