<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ResumeController;
use App\Http\Controllers\HistoryController;

/*
|--------------------------------------------------------------------------
| Resume Analyzer Routes (guests + authenticated users)
|--------------------------------------------------------------------------
*/

Route::get('/', [ResumeController::class, 'index'])->name('resume.index');

Route::get('/upload', function () {
    return redirect()->route('resume.index');
});

Route::post('/upload', [ResumeController::class, 'upload'])->name('resume.upload');

Route::post('/chat/message', [ResumeController::class, 'chatMessage'])->name('chat.message');

Route::post('/chat/save', [ResumeController::class, 'saveChat'])->name('chat.save');

Route::post('/download-report', [ResumeController::class, 'downloadReport'])->name('download.report');

/*
|--------------------------------------------------------------------------
| History Routes (authenticated users only)
|--------------------------------------------------------------------------
*/

Route::middleware('auth')->prefix('history')->name('history.')->group(function () {
    Route::get('/',                              [HistoryController::class, 'index'])          ->name('index');
    Route::get('/{chatSession}',                 [HistoryController::class, 'show'])           ->name('show');
    Route::post('/{chatSession}/download',       [HistoryController::class, 'downloadReport']) ->name('download');
    Route::delete('/{chatSession}',              [HistoryController::class, 'destroy'])        ->name('destroy');
});

/*
|--------------------------------------------------------------------------
| Laravel Breeze Auth Routes
| (auto-generated by: php artisan breeze:install blade)
|--------------------------------------------------------------------------
*/
Route::get('/privacy', fn() => view('privacy'))->name('privacy');
Route::get('/terms', fn() => view('terms'))->name('terms');
require __DIR__.'/auth.php';